// App.tsx — AppShell version with FusionShell layout. Generated by scaffold-appshell.
import { HashRouter, Routes, Route, Outlet, Navigate } from 'react-router-dom'
import ErrorBoundary from './ErrorBoundary'
import { FusionProvider } from './contexts/fusion'
import FusionShell from './components/FusionShell'
import { FUSION_CONFIG } from './navigation'
import OpenReturnPage from './pages/OpenReturnPage'
import DataReviewPage from './pages/DataReviewPage'
import DataReviewPopout from './pages/DataReviewPopout'
import SmartReturnPage from './pages/SmartReturnPage'
import WorkspacePage from './pages/WorkspacePage'
import HomePage from './pages/HomePage'
import NotFoundPage from './pages/NotFoundPage'

function AppLayout() {
  return (
    <FusionShell businessName={FUSION_CONFIG.businessName}>
      <Outlet />
    </FusionShell>
  )
}

// APP_PAGES — add new app page routes here (managed by /page skill)
const APP_PAGES: { path: string; component: React.ComponentType }[] = []

export default function App() {
  return (
    <ErrorBoundary>
      <HashRouter>
        <FusionProvider pathPrefix={FUSION_CONFIG.pathPrefix || ''}>
          <Routes>
            <Route path="/import-hub" element={<OpenReturnPage />} />
            <Route path="/smart-return" element={<SmartReturnPage />} />
            <Route path="/data-review" element={<DataReviewPage />} />
            <Route path="/data-review-popout" element={<DataReviewPopout />} />
            <Route element={<AppLayout />}>
              <Route path="/" element={<Navigate to="/import-hub" replace />} />
              <Route path="/home" element={<HomePage />} />
              <Route path="/workspace" element={<WorkspacePage />} />
              {APP_PAGES.map(({ path, component: Page }) => (
                <Route key={path} path={`/app/${path}`} element={<Page />} />
              ))}
              <Route path="/app/*" element={<NotFoundPage />} />
              <Route path="*" element={<NotFoundPage />} />
            </Route>
          </Routes>
        </FusionProvider>
      </HashRouter>
    </ErrorBoundary>
  )
}
